### PR TITLE
Mutiple copy

### PR DESCRIPTION
**Pull request by wutw**
Chrome copy occasional content is not updated

### CODE REVIEW

**Comment by sudodoki** [comment]
@wutw can you come up with reprocase in which you've seen this not working? What you are doing here seems to me slightly too forcing to whatever browser is doing by default

**Comment by wutw** [comment]
I encountered a problem, after copying across pages, I got the last copied value instead of the latest value, so I did some defense

**Comment by wutw** [comment]
@sudodoki

**Comment by sudodoki** [comment]
>I got the last copied value instead of the latest value

Sorry, I don't get this part

**Comment by sudodoki** [comment]
@wutw please provide reprocase / browser info for this issue to occur. There was issue with IE11, you might have encountered if you used copy in different ways (with format and without), which should be fixed via #93. Closing this for now, feel free to let me know further details and we can reopen and fix it.

**Pull request closed without merging**
