### PR TITLE
Copy with a MIME type option

### PR DESCRIPTION
**Pull request by sloanesturz**
I needed a similar feature to the PR in #77 -- but I wanted to copy HTML instead of text/plain. So I implemented it in the way that @sudodoki recommended. We have been using this in our application for several weeks and it works correctly.

### CODE REVIEW

**Comment by sudodoki** [comment]
I'll try to get back to this by the end of the weekend, might also need to update README.md, but thanks for doing this 🙇

**Comment by sloanesturz** [comment]
I updated the README - thanks for pointing me there as well.

**Comment by sudodoki** [comment]
Looks great, gonna merge and possibly add some minor things to readme

**Comment by sudodoki** [comment]
Updated readme a bit https://github.com/sudodoki/copy-to-clipboard/commit/db1473758e3a528fed9dbfca51a890708ac103e9 hope this is okay with you

**Comment by sudodoki** [comment]
published in https://github.com/sudodoki/copy-to-clipboard/releases/tag/v3.2.0

**Pull request merged**
