### PR TITLE
Make server-side rendering great again

### LINKED ISSUE #39: Breaks universal rendering
https://github.com/sudodoki/copy-to-clipboard/commit/a3e3d1547d5f5d65659cc621cdcdcaf5c3720510#diff-168726dbe96b3ce427e7fedce31bb0bc change breaks universal rendering since `navigator` is undefined on the server.
Usually it worked fine since we were copying after some user interactions and `copy-to-clipboard` was never run on the server.

### PR DESCRIPTION
**Pull request by nkbt**
Fixes #39

### CODE REVIEW

**Comment by nkbt** [comment]
I checked with my server-side tests with removed `global.navigator = {}` hack, works perfectly fine

**Comment by goldensunliu** [comment]
looks good to me.  CI check is failing on SauceLab credentials: https://travis-ci.org/sudodoki/copy-to-clipboard/jobs/142635817#L240

**Comment by nkbt** [comment]
Ping @sudodoki ;)

**Comment by sudodoki** [comment]
Hell of the week here, will take a look as soon as I get a spare hour :wink:
7 июля 2016 г. 2:49 PM пользователь "Nik Butenko" <notifications@github.com>
написал:

**Comment by nkbt** [comment]
Cheers 🍻

**Comment by sudodoki** [comment]
Available as part of https://github.com/sudodoki/copy-to-clipboard/releases/tag/v3.0.4.

**Comment by nkbt** [comment]
Thank you!

**Pull request merged**
