### PR TITLE
Force a text/plain copy to make it easier to work with word processors

### LINKED ISSUE #46: Copied text has a grey background when pasted into gmail or google docs.
This is pretty much the same issue as [#43](https://github.com/sudodoki/copy-to-clipboard/issues/43) but now the background is grey instead of yellow. Do you know what might cause this and if there is a way to make that not happen?

### PR DESCRIPTION
**Pull request by julienw**
Fixes #46

### CODE REVIEW

**Comment by julienw** [comment]
On my side it seems to fix the problem, but please test it on your side as well!

**Comment by sudodoki** [comment]
Not sure about this one, I would prefer to fix #46 by some css (it's a pity `mark.style.all = 'unset'` doesn't help), or by setting format on clipboard data if there's some mode like `plaintext=true` arg passed. And just using clipboard.setData as done in https://github.com/sudodoki/copy-to-clipboard/pull/77/files#diff-168726dbe96b3ce427e7fedce31bb0bcL63 is kinda redoing the same effort. I would prefer to rely on execCommand by default. Possibly, https://github.com/sudodoki/copy-to-clipboard/pull/26 might help (switching to textarea) but if we are dealing with html content, something like DOMParser + textContent (as mentioned [here]) might be an answer 🤔

**Comment by julienw** [comment]
I tried a textarea and it didn't seem to help with this issue, but maybe I did it in a wrong way.

I also tried a white background, and this is mostly OK, except it does a white background on the text when pasting in a colorful document background.

We can also use, if existing, the new api [Clipboard.writeText](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/WriteText).

But I like the solution I proposed here because:
- it fixes the problem completely.
- it is simple 
- It is supported everywhere execCommand is supported. (or so I think)

**Comment by julienw** [comment]
> It is supported everywhere execCommand is supported. 

Or rather supported everywhere the copy event is supported.

**Comment by julienw** [comment]
The root issue, I think, is that chrome copies the default page background. That's why `unset: all` doesn't work.
 I believe this is a bug in Chrome but well... We have to deal with it :)

**Comment by julienw** [comment]
Also I believe it's important to fix it now because with the other PR I wrote the workaround isn't possible anymore.

**Comment by sudodoki** [comment]
Then I would ask of you to add format as argument (might also require linking to proper values that can be used as format argument, updating readme and updating typing). Does it make sense? In case someone relied on rich text copying. Can you do that, please?

**Comment by sudodoki** [comment]
Closed in favour of #79 Thanks for bringing this up!

**Comment by julienw** [comment]
yeah, I had ideas to implement this, just was too busy, sorry about that :(

But I don't think #79 fixes the original problem in Chrome, actually, as it does nothing if we pass nothing (the default situation), and also I think it won't work properly if somebody passes "text" (as it says the default is), and also it doesn't control how it will look like as HTML.

I have some time now, I can try to rebase on top of that patch and see if I can come up with anything.

**Comment by julienw** [comment]
>  if somebody passes "text" 

Ah, I see you changed the README, this makes it better indeed.

I'd still like to propose another possibility, you'll tell me if you like it.
Especially I think the text/html option shouldn't be the default.

**Pull request closed without merging**
