### PR TITLE
Fix copy with formatting for IE

### PR DESCRIPTION
**Pull request by wdlb**
Hi! When using react-copy-to-clipboard, which is using this copy-to-clipboard module, I've encountered an issue in IE11.

In the function that was attached to the "copy" event using the `mark.addEventListener("copy", function(e) {  ... })` an error is thrown in IE11 due to the `e.clipboardData` being undefined. There's a `try/catch` present, but we do not end up in the `catch` block due to the fact that the error is thrown inside of the callback attached to the "copy" event and not inside of the root level `function copy(text, options) { ... }`.

I fixed this by checking explicitly if the `e.clipboardData` is `undefined`, and using the `window.clipboardData` if this is the case. I had to add some conversion of options as well, as per: https://msdn.microsoft.com/en-us/ie/ms536744(v=vs.94).

Could you have a look at this please? Thanks a lot!

### CODE REVIEW

**Comment by wdlb** [comment]
This PR should solve this issue as well: https://github.com/sudodoki/copy-to-clipboard/issues/84

**Comment by sudodoki** [comment]
At glance, looks good. Let me get back to this when I get time to do the release as well

**Comment by sudodoki** [comment]
And thanks 🙏

**Comment by wdlb** [comment]
You're welcome, thank you for all the time you have invested in this library! I've seen that the travis-ci build failed, should I do something about it? Because it's not entirely clear to me why exactly. Have a nice day!

**Comment by sudodoki** [comment]
@wdlb no, you are good, it originally failed due to some inconsistencies between browsers, and I guess now it's because saucelab account expired or something like that.

**Pull request merged**
