### PR TITLE
Turn into ES6

### PR DESCRIPTION
**Pull request by vp2177**

### CODE REVIEW

**Comment by vp2177** [comment]
The actual `copy()` is not changed, just indented. If you prefer I can modify this to remove the indentation, as GitHub's diff doesn't seem very smart

**Comment by sudodoki** [comment]
Will take a closer look when I get back from vacation. Appreciate the
contribution :bow:
14 янв. 2016 г. 7:46 PM пользователь "Peter V" <notifications@github.com>
написал:

**Comment by sudodoki** [comment]
Bundling: most of the time this would be used with browserify/webpack or directly in browser. So it should probably just support 2 cases: cjs (which it does out of the box) and browser. I'm not keen on using require.js and didn't see request to support that, so would probably just expose function in global.
As for the es6: I don't want dependencies of this module to bloat, so I would reconsider moving to es6 when modules would be supported better natively so we could live w/o babel.

Let me know your thoughts about this.

**Comment by vp2177** [comment]
Well we _need_ require.js, that is the reason for these pull requests.
ES6 is not necessary then, I can convert it back to ES5/CommonJS, which would then be Webpacked to UMD

**Comment by sudodoki** [comment]
What about using default shim thing for require.js? Is that not working for
you?
10 февр. 2016 г. 12:35 PM пользователь "Peter V" <notifications@github.com>
написал:

**Pull request closed without merging**
