### PR TITLE
Add options.cb: callback to be executed after copying

### LINKED ISSUE #20: Callback if copy successful
Just curious if there's a way to detect if copy is successful? If so can we expose a callback function option to let users perform custom actions on successful copy? Thanks!

### PR DESCRIPTION
**Pull request by sudodoki**
Closes #20. Actually, it will be executed after every execution.
TODO: decide whether need to add another error handler to propagate error into callback (node-style)

### CODE REVIEW

**Comment by shvaikalesh** [comment]
Why do we need a callback after all? `copy` function is all synchronous.

**Comment by sudodoki** [comment]
@shvaikalesh think I just messed this feature up. `¯\_(ツ)_/¯` Should have been `cb(err)` in case there's an actual error while copying, but it never happens with fallback strategy. Original request in #20 was about 'copied' being shown in https://github.com/nkbt/react-copy-to-clipboard when it actually didn't copy. That behaviour from what I've seen is occuring when you try to copy 'undefined'. Maybe, should just do 
`cb(TypeError('No text to copy specified'))` in case text is `== undefined`

**Comment by shvaikalesh** [comment]
> `cb(TypeError('No text to copy specified')) in case text is == undefined`

That is one way of building APIs. However, JavaScript is weakly typed lang, so I would rather follow conventions of its stdlib and coerce types.

Bottom line: no reason for callback here. Either `typeof == 'string' || throw` or pass `text` as is.

**Comment by sudodoki** [comment]
@shvaikalesh seems like it even would not copy anything using `execCommand` in case text is falsey.

**Comment by sudodoki** [comment]
Would be removing this option in https://github.com/sudodoki/copy-to-clipboard/pull/25. Instead in case @philster provide examples when [copy is not successful](https://github.com/sudodoki/copy-to-clipboard/issues/20#issuecomment-190453160) - might add a guard condition to prevent 'successful yet not successful copy'.

**Comment by philster** [comment]
@sudodoki I am unable to correctly determine if a copy is successful or not via `execCommand`, so a callback is probably not useful in this case. Please go ahead and remove the option.

**Pull request merged**
