### PR TITLE
Prevent the copy event from bubbling up to body

### LINKED ISSUE #75: Consider replacing the use of `selectNode` by `selectAllChildren` or `selectNodeContents`
In the current version of the library, we select the text to be copied by using this code:
```js
range.selectNode(mark);
selection.addRange(range);
```
The problem with `selectNode` is that it selects the Node itself, which has comme unfortunate consequence that the Selection object gets `focusNode` and `anchorNode` set to `body` which is the parent of the element. This is expected [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/range/selectNode):

> The Range.selectNode() method sets the Range to contain the Node and its contents. The parent Node of the start and end of the Range will be the same as the parent of the referenceNode.

The direct consequence is that the `copy` event's target is then `body`, while it would be better if it was the range itself (more about that below).

An easy way to fix it is to replace `range.selectNode` by `range.selectNodeContents`. Another way is to replace using a `range` and directly use `selection.selectAllChildren`, but then we need to also change (maybe simplify?) the way we remove the selection by always calling `selection.removeAllRanges()`.

Now, why is that useful ?
Because I think the component should stop the propagation of the "copy" event by adding something like:
```js
    mark.addEventListener('copy', e => e.stopPropagation());
```
This is useful because applications commonly add a `copy` event handler on the `body` to handle ctrl-c operations (that's what we do in our app indeed!). It's on `body` because there are some cross-browser issues about what the `target` should be in some situations.

But in my opinion the `copy` event provoked by `copy-to-clipboard` is an unfortunate side effect of the method we use to copy, and so it should just be invisible to the outer code.

I'll be happy to do the patch if you think the changes are useful.

### PR DESCRIPTION
**Pull request by julienw**
Fixes #75

### CODE REVIEW

**Comment by julienw** [comment]
I didn't know how to run the tests (`npm test` runs Firefox but then nothing happens on my computer) so I didn't add any. But I'd be happy to with some guidance.

**Comment by sudodoki** [comment]
Thanks! Pulled via ad759b00dfc0133ee88e5c4788b7f10db8d3ac99

**Comment by sudodoki** [comment]
Wonder whether https://github.com/sudodoki/copy-to-clipboard/issues/46#issuecomment-287925065 workaround will work after this (although it performs copying by that code snippet already) 🤔

**Comment by julienw** [comment]
ah yes indeed :/

**Comment by julienw** [comment]
Maybe we can add this workaround right in the copy event handler, what do you think?
Unless there's another way to fix this...

**Comment by julienw** [comment]
Another possibility is to set a white background to the span. Then the text would have a white background instead of a grey background. Still not perfect but better.

**Comment by julienw** [comment]
Actually their workaround doesn't seem to work at all anyway. I'd suggest to just put a background to white.

**Comment by julienw** [comment]
Ah yes it works, I had a bad state in my gdocs. Let me do a quick PR :)

**Pull request closed without merging**
